# See
# https://docs.wandb.ai/guides/sweeps/define-sweep-configuration
# for more options
program: train.py
name: wandb_sample
method: bayes
metric:
  goal: minimize
  name: validation_loss
parameters:
  learning_rate:
    min: 0.0001
    max: 0.1
  batch_size:
    values: [16, 32, 64]
  epochs:
    values: [5, 10, 15]
  optimizer:
    values: ["adam", "sgd"]
